### ISSUE TITLE
Version parameter seems to be ignored by GetEsp8266Update

### ISSUE THREAD

**Issue by arkhipenko** [otadrive/ESP8266-OTA-Blinker#1]
It seems the GetEsp8266Update method returns the same version binary no matter what I pass as version parameter. 

Please check: 
http://otadrive.com/DeviceApi/GetEsp8266Update?k=63556a3e-5467-4ad7-9190-2e793f264245&s=FA56E6ED0&v=1.0.0.1

http://otadrive.com/DeviceApi/GetEsp8266Update?k=63556a3e-5467-4ad7-9190-2e793f264245&s=FA56E6ED0&v=13

Returns the same "Version 1"  "binary" that I associated with the device. 

Is that how it is supposed to work?

**Comment by mostafahk** [comment]
Thank you for your reply
The GetEsp8266Update method returns version who admin selects for device group. The version parameter is not for asking a version, Its just status of device current version, server returns HTTP 304 if current version of device is same as selected version.

if you want to change device version, you should change firmware for group witch device is in.

![Capture](https://user-images.githubusercontent.com/30733372/78408935-a6a23980-761d-11ea-8d7e-fc97e0c52898.PNG)


you can also change group of your device like this

![Capture2](https://user-images.githubusercontent.com/30733372/78408929-a2761c00-761d-11ea-9360-e9fb0186f2fb.PNG)

**Comment by arkhipenko** [comment]
OK. Got it. Let me check with the actual hardware. 
So far testing from Postman the binary is sent every time, even if asking for the same version.
I suspect I might not be setting the header attributes correctly as I am not getting HTTP 304, but the binary every time.

**Comment by mostafahk** [comment]
Be careful about passing version to server. It should pass exactly same characters in query string as you defined in firmware section of your product.

See my test result :

![Untitled](https://user-images.githubusercontent.com/30733372/78745779-6377fb80-797a-11ea-9715-8d61d0c8d9c3.png)

**Comment by arkhipenko** [comment]
Tested yesterday and working as described. Thank you for clarifications.
