### ISSUE TITLE
GetConfig returns "Update failed!"

### ISSUE THREAD

**Issue by tatuiot** [otadrive/ESP8266-OTA-Blinker#3]
Hi thanks for this great tool.
I managed to update the firmware with no issues.

But I replicated the doUpdate() funciton changing the url by http://otadrive.com/DeviceApi/GetConfig?k=
It does not make sense to me, how will replace the exact same variable...? I am lost... and it is a great feature...  but honestly I am missing something and I wonder what it is.

**Comment by otadrive** [comment]
Hi
Usage of the GetConfig is not like what you tested. We will provide new sample and documentation in next week.
